### PR TITLE
added i18n help files

### PR DESCRIPTION
**Pull request by heikokue**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes
separation of help-parts to separate en-US locales html files.
no content changes.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
Hi thanks for all these - please note that we rarely update/maintain some of these nodes as they were "gifted" to us by another group - so while I'm happy for any contributions please don't bust a gut translating any you don't actually need to.

It's gong to take a while to go through them all before we can merge them - it would have been easier if a) they had been discussed on the forum first and b) were in smaller chunks of a few nodes at a time.

**Comment by heikokue** [comment]
Hello! Oh, sorry for my endeavor to improve Node-RED. We have current Corona lockdown in Germany and I tried to spent my time for are meaningful job. Up to now I spent over 50 hours to improve the german UI.

Regarding a) The plan to improve the DE translation is already discussed in Slack channel #18n-de and in the Forum https://discourse.nodered.org/t/german-translation-anyone-interested/38209/4. The feedback is quite small...

Regarding b) This PR has **no** content change. Only the help text parts in the of the node's main html files are moved into separated html files in locales/en-US folder.
This shall be the 1st step, before as 2nd step the DE translations shall be added in locales/de folder in separate PRs.

How to continue?
Shall I split this PR node for node?

**Comment by dceejay** [comment]
Hi 
no problem - I will accept this PR as is - it will just take some time to check through it all. When it comes to actual translations - please only do the ones you need to start with - as I said many of the others are somewhat "legacy" so may not be needed at all (eg the tfl API has lng since stopped working and do foursquare still exist ? so check before actually translating.

**Comment by heikokue** [comment]
yes, I agree, I want only translate nodes, which are popular here in Germany and which has high download rates, checked on https://flows.nodered.org.
Escpecially in social nodes of providers, which are obselete or unknown in Germany, I will invest no efforts.

**Pull request merged**
