### PR TITLE
Language Select

### PR DESCRIPTION
**Pull request by kuehnelbs**
New Language Select with languages available by darksky API

### CODE REVIEW

**Comment by dceejay** [comment]
Thanks  @kuehnelbs 
new version 0.1.13 pushed to npm

**Comment by Paul-Reed** [comment]
Hi @kuehnelbs 
Are you aware of issue https://github.com/node-red/node-red-web-nodes/issues/161

Thanks

**Comment by dceejay** [comment]
applied the patch mentioned

**Comment by Paul-Reed** [comment]
Not checked the language selection, but the patch has fixed the loading issue. Now loads & functions OK with no log or browser errors.
Please close
Thank you.

**Pull request merged**
