### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by papettoTV**
Fix typo 'ap-norteast-1' to 'ap-northeast-1'

### CODE REVIEW

**Comment by dceejay** [comment]
Hi - thanks for this... Are you able to accept the license/cla ?

**Comment by papettoTV** [comment]
I signed CLA but "not signed yet" mark is not disapeared

**Comment by dceejay** [comment]
Hi,
 odd -- can you check that the email used was the same as your code is signed with ?

**Comment by papettoTV** [comment]
My github email was different CLA signed email, so I updated github email same as CLA email, but status is not changed. ummm

**Comment by knolleary** [comment]
The issue is the email associated with the commits in this PR - e.yokota@uhuru.jp. Changing your email associated with your github account won't change the commit history.

So, options are:

1. sign the cla with the email you used to commit with.
2. abandon this PR and redo it having set you [git profile to use your preferred email](https://help.github.com/articles/setting-your-commit-email-address-in-git/)

**Comment by papettoTV** [comment]
@knolleary 
Thx , I understood and retry commit. So all check have passed.

**Pull request merged**
